name = "Vitae"
license = "MIT"
licenselink = "https://github.com/3ld0ct0r/hugo-vitae/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/3ld0ct0r/hugo-vitae/"
tags = ["cv", "resume"]
features = ["one page", "resume"]
min_version = 0.17
